/**
 * build.js — runs at Vercel deploy time
 * Reads SUPABASE_URL and SUPABASE_ANON_KEY from Vercel environment variables
 * and writes them into env-config.js so the browser can use them.
 *
 * Set these in: Vercel Dashboard → your project → Settings → Environment Variables
 *   SUPABASE_URL      = https://your-project.supabase.co
 *   SUPABASE_ANON_KEY = eyJ...your anon key...
 */

const fs = require('fs');

const url  = process.env.SUPABASE_URL      || '';
const anon = process.env.SUPABASE_ANON_KEY || '';

if (!url || !anon) {
  console.warn(
    '\n⚠️  SUPABASE_URL or SUPABASE_ANON_KEY not set in environment.\n' +
    '   Add them in Vercel → Settings → Environment Variables.\n'
  );
}

const output = `/* Auto-generated by build.js — do not edit manually */
window.SUPABASE_URL  = "${url}";
window.SUPABASE_ANON = "${anon}";
`;

fs.writeFileSync('env-config.js', output);
console.log('✓ env-config.js written');
