// Combined UX_QUESTIONS from all categories
const UX_QUESTIONS = [
  ...UX_UX_RESEARCH,
  ...UX_VISUAL_DESIGN,
  ...UX_EMOTIONAL_DESIGN,
  ...UX_UX_LAWS,
  ...UX_INTERACTION_DESIGN,
  ...UX_INFORMATION_ARCHITECTURE,
  ...UX_ACCESSIBILITY,
  ...UX_GESTALT,
  ...UX_HEURISTICS,
  ...UX_PROTOTYPING,
  ...UX_DESIGN_SYSTEMS,
  ...UX_PSYCHOLOGY,
  ...UX_ETHICS___PATTERNS,
  ...UX_TYPOGRAPHY,
  ...UX_COLOR_THEORY,
  ...UX_GENERAL_THEORY,
];
