// Combined UX_QUESTIONS from all categories (PDF syllabus + theory supplements)
const UX_QUESTIONS = [
  ...UX_UX_RESEARCH,
  ...UX_VISUAL_DESIGN,
  ...UX_EMOTIONAL_DESIGN,
  ...UX_UX_LAWS,
  ...UX_INTERACTION_DESIGN,
  ...UX_INFORMATION_ARCHITECTURE,
  ...UX_ACCESSIBILITY,
  ...UX_GESTALT,
  ...UX_HEURISTICS,
  ...UX_PROTOTYPING,
  ...UX_DESIGN_SYSTEMS,
  ...UX_PSYCHOLOGY,
  ...UX_ETHICS___PATTERNS,
  ...UX_TYPOGRAPHY,
  ...UX_COLOR_THEORY,
  // General theory supplements
  ...UX_UX_PRINCIPLES,
  ...UX_UI_COMPONENTS,
  ...UX_ACCESSIBILITY_THEORY,
  ...UX_UX_RESEARCH_THEORY,
  ...UX_TYPOGRAPHY_THEORY,
  ...UX_GESTALT_THEORY,
  ...UX_INTERACTION_DESIGN_THEORY,
  ...UX_UX_LAWS_THEORY,
  ...UX_PROTOTYPING_THEORY,
  ...UX_INFORMATION_ARCHITECTURE_THEORY,
  ...UX_VISUAL_DESIGN_THEORY,
  ...UX_USABILITY_TESTING,
  ...UX_UX_STRATEGY,
  ...UX_HEURISTICS_THEORY,
  // Visual questions
  ...VISQ_INTERACTION_DESIGN,
  ...VISQ_INFORMATION_ARCHITECTURE,
  ...VISQ_GESTALT,
  ...VISQ_UI_COMPONENTS,
  ...VISQ_PROTOTYPING,
];

const INTERVIEW_QUESTIONS = [
  ...UX_UX_PRINCIPLES,
  ...UX_UI_COMPONENTS,
  ...UX_ACCESSIBILITY_THEORY,
  ...UX_UX_RESEARCH_THEORY,
  ...UX_TYPOGRAPHY_THEORY,
  ...UX_GESTALT_THEORY,
  ...UX_INTERACTION_DESIGN_THEORY,
  ...UX_UX_LAWS_THEORY,
  ...UX_PROTOTYPING_THEORY,
  ...UX_INFORMATION_ARCHITECTURE_THEORY,
  ...UX_VISUAL_DESIGN_THEORY,
  ...UX_USABILITY_TESTING,
  ...UX_UX_STRATEGY,
  ...UX_HEURISTICS_THEORY,
  ...VISQ_INTERACTION_DESIGN,
  ...VISQ_INFORMATION_ARCHITECTURE,
  ...VISQ_GESTALT,
  ...VISQ_UI_COMPONENTS,
  ...VISQ_PROTOTYPING,
];

const LESSON_MAP = [
  { id: 2, title: "Understanding of UX-UI", questions: UX_UX_RESEARCH.slice(0, 15) },
  { id: 3, title: "Emotional Design", questions: UX_EMOTIONAL_DESIGN },
  { id: 4, title: "UX Psychology", questions: UX_PSYCHOLOGY },
  { id: 5, title: "Project Topic Selection", questions: UX_UX_RESEARCH.slice(15, 20) },
  { id: "5.1", title: "Requirement Gathering", questions: UX_UX_RESEARCH.slice(20, 25) },
  { id: 6, title: "Planning and Strategy", questions: UX_UX_RESEARCH.slice(25, 30) },
  { id: 7, title: "Interviews", questions: UX_UX_RESEARCH.slice(30, 35) },
  { id: 9, title: "User Research Methods", questions: UX_UX_RESEARCH.slice(35, 40) },
  { id: 10, title: "User Persona", questions: UX_UX_RESEARCH.slice(40, 45) },
  { id: 11, title: "Empathy Map", questions: UX_UX_RESEARCH.slice(45, 50) },
  { id: 12, title: "Customer Journey Map", questions: UX_UX_RESEARCH.slice(50, 55) },
  { id: 13, title: "Define", questions: UX_UX_RESEARCH.slice(55, 59) },
  { id: 14, title: "Competitive Analysis", questions: UX_VISUAL_DESIGN.slice(0, 5) },
  { id: 15, title: "Ideation", questions: UX_VISUAL_DESIGN.slice(5, 10) },
  { id: 16, title: "User Scenario", questions: UX_INTERACTION_DESIGN.slice(0, 8) },
  { id: 17, title: "User Flow and Task Flow", questions: UX_INTERACTION_DESIGN.slice(8, 16) },
  { id: 18, title: "Information Architecture", questions: UX_INFORMATION_ARCHITECTURE },
  { id: 19, title: "Accessibility", questions: UX_ACCESSIBILITY },
];
